//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Клиенты
    {
        public int ID_клиента { get; set; }
        public string ФИО { get; set; }
        public string Паспорт { get; set; }
        public string Телефон { get; set; }
    }
}
