//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Номера
    {
        public int ID { get; set; }
        public int Тип { get; set; }
        public int Вместимость { get; set; }
        public double Цена { get; set; }
    }
}
