//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудники
    {
        public int ID_сотрудника { get; set; }
        public Nullable<int> ID_должности { get; set; }
        public string Имя { get; set; }
        public string Телефон { get; set; }
    }
}
