//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Учет
    {
        public int ID_Учета { get; set; }
        public int Операция { get; set; }
        public int ID_Номера { get; set; }
        public int ID_Клиента { get; set; }
        public System.DateTime Дата_въезда { get; set; }
        public Nullable<System.DateTime> Дата_выезда { get; set; }
        public double Цена { get; set; }
        public int Сотрудник { get; set; }
    }
}
